#!/usr/bin/env python3
"""Desktop GUI for creating IGV BedGraph/BigWig tracks from SAM files."""

from __future__ import annotations

import os
import shlex
import shutil
import signal
import subprocess
import sys
import threading
import webbrowser
from dataclasses import dataclass
from pathlib import Path

import tkinter as tk
from tkinter import filedialog, messagebox, ttk


APP_TITLE = "SAM → IGV Tracks"
PROJECT_URL = "https://github.com/guydoshlab/ribofootPrinter2"


def shell_quote(value: str | Path) -> str:
    return shlex.quote(str(value))


@dataclass(frozen=True)
class TrackJob:
    sam_file: Path
    output_dir: Path
    make_5prime: bool
    shift_5prime: int
    make_3prime: bool
    shift_3prime: int
    make_bigwig: bool

    @property
    def prefix(self) -> str:
        return self.sam_file.stem

    @property
    def bedgraph_5prime_path(self) -> Path:
        shifted = f"_shift{self.shift_5prime:+d}" if self.shift_5prime else ""
        return self.output_dir / f"{self.prefix}_5prime{shifted}.bedgraph"

    @property
    def bedgraph_3prime_path(self) -> Path:
        shifted = f"_shift{self.shift_3prime:+d}" if self.shift_3prime else ""
        return self.output_dir / f"{self.prefix}_3prime{shifted}.bedgraph"

    @property
    def bigwig_path(self) -> Path:
        return self.output_dir / f"{self.prefix}_coverage.bw"

    @property
    def script_path(self) -> Path:
        return self.output_dir / f"{self.prefix}_commands.sh"

    @property
    def log_path(self) -> Path:
        return self.output_dir / f"{self.prefix}_run.log"

    def outputs(self) -> list[Path]:
        result: list[Path] = []
        if self.make_5prime:
            result.append(self.bedgraph_5prime_path)
        if self.make_3prime:
            result.append(self.bedgraph_3prime_path)
        if self.make_bigwig:
            result.append(self.bigwig_path)
        result.extend((self.script_path, self.log_path))
        return result


def validate_job(job: TrackJob) -> list[str]:
    errors: list[str] = []
    if not job.sam_file.is_file():
        errors.append("Choose an existing SAM input file.")
    elif job.sam_file.suffix.lower() != ".sam":
        errors.append("The input file must have a .sam extension.")
    if not job.output_dir.is_dir():
        errors.append("Choose an existing output directory.")
    if not (job.make_5prime or job.make_3prime or job.make_bigwig):
        errors.append("Select 5′ BedGraph, 3′ BedGraph, BigWig, or a combination.")
    return errors


def build_shell_script(job: TrackJob) -> str:
    """Return the complete, reproducible shell program used for a job."""
    sam = shell_quote(job.sam_file.resolve())
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by igv_track_gui.py",
        f"# Input SAM: {job.sam_file.resolve()}",
        f"# Output directory: {job.output_dir.resolve()}",
        "",
        f"SAM={sam}",
        'WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/ribofootprinter_igv.XXXXXX")"',
        "cleanup() { rm -rf -- \"$WORK_DIR\"; }",
        "trap cleanup EXIT INT TERM",
        'SORTED_BAM="$WORK_DIR/input.sorted.bam"',
        "",
        'echo "Sorting SAM with samtools..."',
        'samtools sort -o "$SORTED_BAM" "$SAM"',
        'echo "Indexing temporary BAM with samtools..."',
        'samtools index "$SORTED_BAM"',
    ]

    if job.make_5prime or job.make_3prime:
        lines += [
            "",
            'echo "Counting mapped alignments with samtools..."',
            'MAPPED_READS="$(samtools view -c -F 4 "$SORTED_BAM")"',
            'if ! [[ "$MAPPED_READS" =~ ^[0-9]+$ ]] || (( MAPPED_READS == 0 )); then',
            '  echo "Error: the SAM file contains no mapped alignments." >&2',
            "  exit 1",
            "fi",
            'SCALE="$(awk -v n="$MAPPED_READS" \'BEGIN { printf "%.12g", 1000000 / n }\')"',
            'echo "Mapped alignments: $MAPPED_READS; RPM scale: $SCALE"',
        ]
        bedgraph_specs = []
        if job.make_5prime:
            bedgraph_specs.append(("5", job.shift_5prime, job.bedgraph_5prime_path))
        if job.make_3prime:
            bedgraph_specs.append(("3", job.shift_3prime, job.bedgraph_3prime_path))
        for end, shift, final_path in bedgraph_specs:
            raw_variable = f'RAW_BEDGRAPH_{end}'
            final_variable = f'FINAL_BEDGRAPH_{end}'
            shifted_variable = f'SHIFTED_BEDGRAPH_{end}'
            lines += [
                "",
                f'{raw_variable}="$WORK_DIR/raw_{end}prime.bedgraph"',
                f"{final_variable}={shell_quote(final_path.resolve())}",
                f'echo "Creating {end}′-assigned BedGraph with bedtools..."',
                f'bedtools genomecov -ibam "$SORTED_BAM" -scale "$SCALE" -bg -{end} > "${raw_variable}"',
            ]
            if shift:
                lines += [
                    f'echo "Shifting {end}′ BedGraph coordinates by {shift:+d} nt..."',
                    f'{shifted_variable}="$WORK_DIR/shifted_{end}prime.bedgraph"',
                    f"awk -v shift={shift} 'BEGIN {{ OFS=\"\\t\" }} {{ start=$2+shift; end=$3+shift; if (start >= 0) print $1,start,end,$4 }}' \"${raw_variable}\" > \"${shifted_variable}\"",
                    f'mv -f -- "${shifted_variable}" "${final_variable}"',
                ]
            else:
                lines.append(f'mv -f -- "${raw_variable}" "${final_variable}"')
            lines.append(f'echo "BedGraph complete: ${final_variable}"')

    if job.make_bigwig:
        lines += [
            "",
            f"FINAL_BIGWIG={shell_quote(job.bigwig_path.resolve())}",
            'TEMP_BIGWIG="$WORK_DIR/coverage.bw"',
            'echo "Creating base-resolution BPM-normalized BigWig with deepTools bamCoverage..."',
            'bamCoverage --bam "$SORTED_BAM" --outFileName "$TEMP_BIGWIG" --binSize 1 --normalizeUsing BPM --numberOfProcessors 4',
            'mv -f -- "$TEMP_BIGWIG" "$FINAL_BIGWIG"',
            'echo "BigWig complete: $FINAL_BIGWIG"',
        ]

    lines += ["", 'echo "All requested tracks completed successfully."', ""]
    return "\n".join(lines)


def required_tools(job: TrackJob) -> list[tuple[str, str]]:
    tools = [("samtools", "samtools")]
    if job.make_5prime or job.make_3prime:
        tools.append(("bedtools", "bedtools"))
    if job.make_bigwig:
        tools.append(("deepTools bamCoverage", "bamCoverage"))
    return tools


class TrackApp(tk.Tk):
    def __init__(self) -> None:
        super().__init__()
        self.title(APP_TITLE)
        self.geometry("900x760")
        self.minsize(780, 650)
        self.process: subprocess.Popen[str] | None = None
        self.worker: threading.Thread | None = None
        self.cancel_requested = threading.Event()
        self.sam_files: list[Path] = []

        self.output_dir_var = tk.StringVar(value=str(Path.cwd().resolve()))
        self.make_5prime_var = tk.BooleanVar(value=True)
        self.make_3prime_var = tk.BooleanVar(value=False)
        self.bigwig_var = tk.BooleanVar(value=False)
        self.shift_5prime_var = tk.StringVar(value="0")
        self.shift_3prime_var = tk.StringVar(value="0")
        self.status_var = tk.StringVar(value="Ready")

        self._configure_style()
        self._build_ui()
        for var in (
            self.output_dir_var,
            self.make_5prime_var,
            self.make_3prime_var,
            self.bigwig_var,
            self.shift_5prime_var,
            self.shift_3prime_var,
        ):
            var.trace_add("write", lambda *_: self._refresh_preview())
        self._refresh_preview()
        self.protocol("WM_DELETE_WINDOW", self._on_close)

    def _configure_style(self) -> None:
        style = ttk.Style(self)
        if "aqua" in style.theme_names():
            style.theme_use("aqua")
        style.configure("Title.TLabel", font=("TkDefaultFont", 19, "bold"))
        style.configure("Subtitle.TLabel", foreground="#555555")
        style.configure("Run.TButton", font=("TkDefaultFont", 12, "bold"), padding=(18, 9))
        style.configure("Section.TLabelframe", padding=12)
        style.configure("Section.TLabelframe.Label", font=("TkDefaultFont", 11, "bold"))

    def _build_ui(self) -> None:
        outer = ttk.Frame(self, padding=20)
        outer.pack(fill="both", expand=True)
        outer.columnconfigure(0, weight=1)

        header = ttk.Frame(outer)
        header.grid(row=0, column=0, sticky="ew")
        header.columnconfigure(0, weight=1)
        ttk.Label(header, text=APP_TITLE, style="Title.TLabel").grid(row=0, column=0, sticky="w")
        ttk.Button(header, text="About", command=self._show_about).grid(row=0, column=1, sticky="e")
        ttk.Label(
            outer,
            text="Create RPM-normalized end-assigned BedGraph and BPM-normalized coverage BigWig tracks.",
            style="Subtitle.TLabel",
        ).grid(row=1, column=0, sticky="w", pady=(2, 16))

        files = ttk.LabelFrame(outer, text="Files", style="Section.TLabelframe")
        files.grid(row=2, column=0, sticky="ew")
        files.columnconfigure(1, weight=1)
        ttk.Label(files, text="Input SAM files").grid(row=0, column=0, sticky="nw", padx=(0, 10), pady=5)
        sam_frame = ttk.Frame(files)
        sam_frame.grid(row=0, column=1, sticky="ew", pady=5)
        sam_frame.columnconfigure(0, weight=1)
        self.sam_listbox = tk.Listbox(sam_frame, height=4, selectmode="extended", exportselection=False)
        self.sam_listbox.grid(row=0, column=0, sticky="ew")
        sam_scrollbar = ttk.Scrollbar(sam_frame, orient="vertical", command=self.sam_listbox.yview)
        sam_scrollbar.grid(row=0, column=1, sticky="ns")
        self.sam_listbox.configure(yscrollcommand=sam_scrollbar.set)
        sam_actions = ttk.Frame(files)
        sam_actions.grid(row=0, column=2, sticky="n", padx=(8, 0), pady=5)
        ttk.Button(sam_actions, text="Choose…", command=self._browse_sam).pack(fill="x")
        ttk.Button(sam_actions, text="Remove", command=self._remove_selected_sams).pack(fill="x", pady=(6, 0))
        ttk.Label(files, text="Output folder").grid(row=1, column=0, sticky="w", padx=(0, 10), pady=5)
        ttk.Entry(files, textvariable=self.output_dir_var).grid(row=1, column=1, sticky="ew", pady=5)
        ttk.Button(files, text="Browse…", command=self._browse_output_dir).grid(row=1, column=2, padx=(8, 0), pady=5)

        modes = ttk.LabelFrame(outer, text="Tracks", style="Section.TLabelframe")
        modes.grid(row=3, column=0, sticky="ew", pady=(14, 0))
        modes.columnconfigure(1, weight=1)

        ttk.Label(modes, text="BedGraph — single-nucleotide end assignment").grid(
            row=0, column=0, columnspan=3, sticky="w"
        )
        self.five_prime_frame = ttk.Frame(modes)
        self.five_prime_frame.grid(row=1, column=0, columnspan=3, sticky="w", padx=(28, 0), pady=(6, 3))
        ttk.Checkbutton(self.five_prime_frame, text="5′ end", variable=self.make_5prime_var).pack(side="left")
        ttk.Label(self.five_prime_frame, text="Shift (nt)").pack(side="left", padx=(22, 6))
        self.shift_5prime_spinbox = ttk.Spinbox(
            self.five_prime_frame, from_=-10000, to=10000, textvariable=self.shift_5prime_var, width=8
        )
        self.shift_5prime_spinbox.pack(side="left")

        self.three_prime_frame = ttk.Frame(modes)
        self.three_prime_frame.grid(row=2, column=0, columnspan=3, sticky="w", padx=(28, 0), pady=(3, 10))
        ttk.Checkbutton(self.three_prime_frame, text="3′ end", variable=self.make_3prime_var).pack(side="left")
        ttk.Label(self.three_prime_frame, text="Shift (nt)").pack(side="left", padx=(22, 6))
        self.shift_3prime_spinbox = ttk.Spinbox(
            self.three_prime_frame, from_=-10000, to=10000, textvariable=self.shift_3prime_var, width=8
        )
        self.shift_3prime_spinbox.pack(side="left")
        ttk.Label(modes, text="Positive shifts move coordinates to the right; negative shifts move them left.", style="Subtitle.TLabel").grid(
            row=3, column=0, columnspan=3, sticky="w", padx=(28, 0), pady=(0, 8)
        )

        ttk.Checkbutton(modes, text="BigWig — uniform read coverage", variable=self.bigwig_var).grid(
            row=4, column=0, columnspan=3, sticky="w"
        )

        preview = ttk.LabelFrame(outer, text="Full output paths", style="Section.TLabelframe")
        preview.grid(row=4, column=0, sticky="ew", pady=(14, 0))
        preview.columnconfigure(0, weight=1)
        self.preview = tk.Text(preview, height=7, wrap="word", state="disabled", font=("TkFixedFont", 10))
        self.preview.grid(row=0, column=0, sticky="ew")
        preview_scrollbar = ttk.Scrollbar(preview, orient="vertical", command=self.preview.yview)
        preview_scrollbar.grid(row=0, column=1, sticky="ns")
        self.preview.configure(yscrollcommand=preview_scrollbar.set)

        log_frame = ttk.LabelFrame(outer, text="Run log", style="Section.TLabelframe")
        log_frame.grid(row=5, column=0, sticky="nsew", pady=(14, 0))
        outer.rowconfigure(5, weight=1)
        log_frame.rowconfigure(0, weight=1)
        log_frame.columnconfigure(0, weight=1)
        self.log = tk.Text(log_frame, height=11, wrap="word", state="disabled", font=("TkFixedFont", 10))
        self.log.grid(row=0, column=0, sticky="nsew")
        scrollbar = ttk.Scrollbar(log_frame, orient="vertical", command=self.log.yview)
        scrollbar.grid(row=0, column=1, sticky="ns")
        self.log.configure(yscrollcommand=scrollbar.set)

        actions = ttk.Frame(outer)
        actions.grid(row=6, column=0, sticky="ew", pady=(14, 0))
        actions.columnconfigure(1, weight=1)
        self.run_button = ttk.Button(actions, text="Create tracks", style="Run.TButton", command=self._start)
        self.run_button.grid(row=0, column=0)
        self.cancel_button = ttk.Button(actions, text="Cancel", command=self._cancel, state="disabled")
        self.cancel_button.grid(row=0, column=1, sticky="w", padx=(10, 0))
        ttk.Label(actions, textvariable=self.status_var).grid(row=0, column=2, sticky="e")

    def _show_about(self) -> None:
        about = tk.Toplevel(self)
        about.title("About")
        about.resizable(False, False)
        about.transient(self)

        content = ttk.Frame(about, padding=24)
        content.pack(fill="both", expand=True)
        ttk.Label(content, text="For more information:").pack(anchor="w")
        link = tk.Label(
            content,
            text=PROJECT_URL,
            foreground="#0563C1",
            cursor="hand2",
            font=("TkDefaultFont", 11, "underline"),
        )
        link.pack(anchor="w", pady=(6, 18))
        link.bind("<Button-1>", lambda _event: webbrowser.open(PROJECT_URL))
        ttk.Button(content, text="Close", command=about.destroy).pack(anchor="e")

        about.update_idletasks()
        x = self.winfo_rootx() + max(0, (self.winfo_width() - about.winfo_width()) // 2)
        y = self.winfo_rooty() + max(0, (self.winfo_height() - about.winfo_height()) // 2)
        about.geometry(f"+{x}+{y}")
        about.grab_set()
        about.focus_set()

    def _browse_sam(self) -> None:
        filenames = filedialog.askopenfilenames(
            title="Choose one or more SAM files",
            filetypes=[("SAM files", "*.sam *.SAM"), ("All files", "*")],
        )
        if filenames:
            self.sam_files = [Path(filename).resolve() for filename in filenames]
            self._refresh_sam_list()
            self._refresh_preview()

    def _remove_selected_sams(self) -> None:
        selected = set(self.sam_listbox.curselection())
        self.sam_files = [path for index, path in enumerate(self.sam_files) if index not in selected]
        self._refresh_sam_list()
        self._refresh_preview()

    def _refresh_sam_list(self) -> None:
        self.sam_listbox.delete(0, "end")
        for path in self.sam_files:
            self.sam_listbox.insert("end", str(path))

    def _browse_output_dir(self) -> None:
        dirname = filedialog.askdirectory(title="Choose output folder", mustexist=True)
        if dirname:
            self.output_dir_var.set(str(Path(dirname).resolve()))

    def _read_jobs(self) -> list[TrackJob]:
        try:
            shift_5prime = int(self.shift_5prime_var.get().strip())
        except ValueError:
            shift_5prime = 10**100
        try:
            shift_3prime = int(self.shift_3prime_var.get().strip())
        except ValueError:
            shift_3prime = 10**100
        output_dir = Path(self.output_dir_var.get().strip()).expanduser()
        return [
            TrackJob(
                sam_file=sam_file,
                output_dir=output_dir.resolve(),
                make_5prime=self.make_5prime_var.get(),
                shift_5prime=shift_5prime,
                make_3prime=self.make_3prime_var.get(),
                shift_3prime=shift_3prime,
                make_bigwig=self.bigwig_var.get(),
            )
            for sam_file in self.sam_files
        ]

    def _refresh_preview(self) -> None:
        try:
            jobs = self._read_jobs()
            paths: list[str] = []
            for job in jobs:
                if job.make_5prime:
                    paths.append(f"5′ BedGraph: {job.bedgraph_5prime_path}")
                if job.make_3prime:
                    paths.append(f"3′ BedGraph: {job.bedgraph_3prime_path}")
                if job.make_bigwig:
                    paths.append(f"BigWig:    {job.bigwig_path}")
                paths.append(f"Commands:  {job.script_path}")
                paths.append(f"Log:       {job.log_path}")
                paths.append("")
            self._set_preview("\n".join(paths).rstrip() or "Choose one or more SAM files to preview output paths.")
            self.shift_5prime_spinbox.configure(state="normal" if self.make_5prime_var.get() else "disabled")
            self.shift_3prime_spinbox.configure(state="normal" if self.make_3prime_var.get() else "disabled")
        except Exception:
            self._set_preview("Complete the fields above to preview output paths.")

    def _set_preview(self, text: str) -> None:
        self.preview.configure(state="normal")
        self.preview.delete("1.0", "end")
        self.preview.insert("1.0", text)
        self.preview.configure(state="disabled")

    def _start(self) -> None:
        jobs = self._read_jobs()
        errors: list[str] = []
        if not jobs:
            errors.append("Choose at least one SAM input file.")
        for job in jobs:
            errors.extend(f"{job.sam_file.name}: {error}" for error in validate_job(job))
        if jobs and jobs[0].make_5prime and abs(jobs[0].shift_5prime) > 10000:
            errors.append("The 5′ shift must be an integer from -10000 to 10000.")
        if jobs and jobs[0].make_3prime and abs(jobs[0].shift_3prime) > 10000:
            errors.append("The 3′ shift must be an integer from -10000 to 10000.")
        prefix_counts: dict[str, int] = {}
        for job in jobs:
            key = job.prefix.casefold()
            prefix_counts[key] = prefix_counts.get(key, 0) + 1
        duplicates = sorted({job.prefix for job in jobs if prefix_counts[job.prefix.casefold()] > 1})
        if duplicates:
            errors.append("Selected SAM files have duplicate basenames: " + ", ".join(duplicates))
        if errors:
            messagebox.showerror("Cannot start", "\n".join(f"• {error}" for error in errors))
            return

        missing = [label for label, executable in required_tools(jobs[0]) if shutil.which(executable) is None]
        if missing:
            messagebox.showerror(
                "Missing command-line tools",
                "These required tools are not on PATH:\n\n"
                + "\n".join(f"• {name}" for name in missing)
                + "\n\nInstall them (for example with Bioconda or brew), and then launch this GUI.",
            )
            return

        existing = sorted({path for job in jobs for path in job.outputs() if path.exists()})
        if existing and not messagebox.askyesno(
            "Replace existing outputs?",
            "These files already exist and will be replaced:\n\n" + "\n".join(str(path) for path in existing),
        ):
            return

        try:
            for job in jobs:
                job.script_path.write_text(build_shell_script(job), encoding="utf-8")
                job.script_path.chmod(0o755)
                job.log_path.write_text("", encoding="utf-8")
        except OSError as exc:
            messagebox.showerror("Cannot write outputs", str(exc))
            return

        self._set_running(True)
        self.cancel_requested.clear()
        self._append_log(
            "Saved reproducible command scripts:\n" + "\n".join(str(job.script_path) for job in jobs) + "\n\n"
        )
        self.worker = threading.Thread(target=self._execute_jobs, args=(jobs,), daemon=True)
        self.worker.start()

    def _execute_jobs(self, jobs: list[TrackJob]) -> None:
        completed = 0
        return_code = 0
        failed_job: TrackJob | None = None
        try:
            for index, job in enumerate(jobs, start=1):
                if self.cancel_requested.is_set():
                    return_code = -signal.SIGTERM
                    break
                self.after(0, self.status_var.set, f"Running {index} of {len(jobs)}…")
                self.after(0, self._append_log, f"\n[{index}/{len(jobs)}] {job.sam_file}\n")
                with job.log_path.open("a", encoding="utf-8", buffering=1) as log_handle:
                    kwargs: dict[str, object] = {
                        "args": ["bash", str(job.script_path)],
                        "stdout": subprocess.PIPE,
                        "stderr": subprocess.STDOUT,
                        "text": True,
                        "bufsize": 1,
                    }
                    if os.name == "posix":
                        kwargs["start_new_session"] = True
                    self.process = subprocess.Popen(**kwargs)  # type: ignore[arg-type]
                    assert self.process.stdout is not None
                    for line in self.process.stdout:
                        log_handle.write(line)
                        self.after(0, self._append_log, line)
                    return_code = self.process.wait()
                self.process = None
                if return_code != 0:
                    failed_job = job
                    break
                completed += 1
            self.after(0, self._finished, jobs, completed, return_code, failed_job)
        except Exception as exc:
            self.after(0, self._failed, str(exc))
        finally:
            self.process = None

    def _finished(self, jobs: list[TrackJob], completed: int, return_code: int, failed_job: TrackJob | None) -> None:
        self._set_running(False)
        if return_code == 0 and completed == len(jobs):
            self.status_var.set("Completed")
            messagebox.showinfo(
                "Tracks created",
                f"Completed {completed} SAM file(s).\n\nCreated:\n\n"
                + "\n".join(str(path) for job in jobs for path in job.outputs()),
            )
        elif return_code < 0 or self.cancel_requested.is_set():
            self.status_var.set(f"Cancelled after {completed} of {len(jobs)}")
        else:
            self.status_var.set(f"Failed (exit {return_code})")
            log_path = failed_job.log_path if failed_job else jobs[completed].log_path
            messagebox.showerror(
                "Track creation failed",
                f"Stopped after {completed} of {len(jobs)} SAM files. The command exited with status {return_code}."
                f"\n\nSee the run log:\n{log_path}",
            )

    def _failed(self, detail: str) -> None:
        self._set_running(False)
        self.status_var.set("Failed")
        messagebox.showerror("Track creation failed", detail)

    def _cancel(self) -> None:
        self.cancel_requested.set()
        process = self.process
        if process is None or process.poll() is not None:
            return
        self.status_var.set("Cancelling…")
        if os.name == "posix":
            try:
                os.killpg(process.pid, signal.SIGTERM)
            except ProcessLookupError:
                pass
        else:
            process.terminate()

    def _set_running(self, running: bool) -> None:
        self.run_button.configure(state="disabled" if running else "normal")
        self.cancel_button.configure(state="normal" if running else "disabled")
        if running:
            self.status_var.set("Running…")

    def _append_log(self, text: str) -> None:
        self.log.configure(state="normal")
        self.log.insert("end", text)
        self.log.see("end")
        self.log.configure(state="disabled")

    def _on_close(self) -> None:
        if self.worker is not None and self.worker.is_alive():
            if not messagebox.askyesno("Quit?", "A conversion is running. Cancel it and quit?"):
                return
            self._cancel()
        self.destroy()


def main() -> int:
    try:
        app = TrackApp()
    except tk.TclError as exc:
        print(f"Unable to start the graphical interface: {exc}", file=sys.stderr)
        return 1
    app.mainloop()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
